import { promises as fs } from "node:fs";
import { createReadStream } from "node:fs";
import path from "node:path";
import { env } from "@/env";

const ROOT = path.resolve(env.storageDir);

function resolveSafe(storageKey: string): string {
  // storageKey is generated by us (no user input), but guard against traversal.
  const full = path.resolve(ROOT, storageKey);
  if (!full.startsWith(ROOT + path.sep) && full !== ROOT) {
    throw new Error("Invalid storage key");
  }
  return full;
}

export async function writeBlob(
  storageKey: string,
  data: Buffer | Uint8Array,
): Promise<void> {
  const full = resolveSafe(storageKey);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, data);
}

export async function deleteBlob(storageKey: string): Promise<void> {
  try {
    await fs.unlink(resolveSafe(storageKey));
  } catch (err) {
    // Already gone is fine; surface anything else.
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}

export function readBlobStream(storageKey: string) {
  return createReadStream(resolveSafe(storageKey));
}

export async function readBlob(storageKey: string): Promise<Buffer> {
  return fs.readFile(resolveSafe(storageKey));
}

/** Absolute on-disk path for a blob (used by tools that read by path). */
export function blobPath(storageKey: string): string {
  return resolveSafe(storageKey);
}

export async function blobExists(storageKey: string): Promise<boolean> {
  try {
    await fs.access(resolveSafe(storageKey));
    return true;
  } catch {
    return false;
  }
}
